//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppAPIAuth.SmsSenderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsSenderService.SMSSoap")]
    public interface SMSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreditoResiduo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        ConsoleAppAPIAuth.SmsSenderService.CreditoResiduoResult CreditoResiduo(string UserId, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreditoResiduo", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppAPIAuth.SmsSenderService.CreditoResiduoResult> CreditoResiduoAsync(string UserId, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvioSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        ConsoleAppAPIAuth.SmsSenderService.InvioSmsResult InvioSms(string UserId, string Password, string Mittente, string[] Numeri, string Testo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvioSms", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppAPIAuth.SmsSenderService.InvioSmsResult> InvioSmsAsync(string UserId, string Password, string Mittente, string[] Numeri, string Testo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatoSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        ConsoleAppAPIAuth.SmsSenderService.StatoSmsResult StatoSms(string UserId, string Password, string IdUnivoco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatoSms", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppAPIAuth.SmsSenderService.StatoSmsResult> StatoSmsAsync(string UserId, string Password, string IdUnivoco);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditoResiduoResult : BaseResult {
        
        private long creditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Credito {
            get {
                return this.creditoField;
            }
            set {
                this.creditoField = value;
                this.RaisePropertyChanged("Credito");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatoSmsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvioSmsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditoResiduoResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codiceErroreField;
        
        private string messaggioErroreField;
        
        private bool successoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodiceErrore {
            get {
                return this.codiceErroreField;
            }
            set {
                this.codiceErroreField = value;
                this.RaisePropertyChanged("CodiceErrore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessaggioErrore {
            get {
                return this.messaggioErroreField;
            }
            set {
                this.messaggioErroreField = value;
                this.RaisePropertyChanged("MessaggioErrore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Successo {
            get {
                return this.successoField;
            }
            set {
                this.successoField = value;
                this.RaisePropertyChanged("Successo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatoSms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataOraField;
        
        private string numeroField;
        
        private string statusField;
        
        private string messaggioField;
        
        private string gatewayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataOra {
            get {
                return this.dataOraField;
            }
            set {
                this.dataOraField = value;
                this.RaisePropertyChanged("DataOra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Messaggio {
            get {
                return this.messaggioField;
            }
            set {
                this.messaggioField = value;
                this.RaisePropertyChanged("Messaggio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Gateway {
            get {
                return this.gatewayField;
            }
            set {
                this.gatewayField = value;
                this.RaisePropertyChanged("Gateway");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatoSmsResult : BaseResult {
        
        private StatoSms[] statiSmsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public StatoSms[] StatiSms {
            get {
                return this.statiSmsField;
            }
            set {
                this.statiSmsField = value;
                this.RaisePropertyChanged("StatiSms");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InvioSmsResult : BaseResult {
        
        private string idUnivocoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdUnivoco {
            get {
                return this.idUnivocoField;
            }
            set {
                this.idUnivocoField = value;
                this.RaisePropertyChanged("IdUnivoco");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSSoapChannel : ConsoleAppAPIAuth.SmsSenderService.SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSoapClient : System.ServiceModel.ClientBase<ConsoleAppAPIAuth.SmsSenderService.SMSSoap>, ConsoleAppAPIAuth.SmsSenderService.SMSSoap {
        
        public SMSSoapClient() {
        }
        
        public SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleAppAPIAuth.SmsSenderService.CreditoResiduoResult CreditoResiduo(string UserId, string Password) {
            return base.Channel.CreditoResiduo(UserId, Password);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppAPIAuth.SmsSenderService.CreditoResiduoResult> CreditoResiduoAsync(string UserId, string Password) {
            return base.Channel.CreditoResiduoAsync(UserId, Password);
        }
        
        public ConsoleAppAPIAuth.SmsSenderService.InvioSmsResult InvioSms(string UserId, string Password, string Mittente, string[] Numeri, string Testo) {
            return base.Channel.InvioSms(UserId, Password, Mittente, Numeri, Testo);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppAPIAuth.SmsSenderService.InvioSmsResult> InvioSmsAsync(string UserId, string Password, string Mittente, string[] Numeri, string Testo) {
            return base.Channel.InvioSmsAsync(UserId, Password, Mittente, Numeri, Testo);
        }
        
        public ConsoleAppAPIAuth.SmsSenderService.StatoSmsResult StatoSms(string UserId, string Password, string IdUnivoco) {
            return base.Channel.StatoSms(UserId, Password, IdUnivoco);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppAPIAuth.SmsSenderService.StatoSmsResult> StatoSmsAsync(string UserId, string Password, string IdUnivoco) {
            return base.Channel.StatoSmsAsync(UserId, Password, IdUnivoco);
        }
    }
}
