//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ConsoleNotificheAPI.Database
{

    public partial class APIAUT : XPObject
    {
        string futente;
        [Size(50)]
        public string utente
        {
            get { return futente; }
            set { SetPropertyValue<string>(nameof(utente), ref futente, value); }
        }
        string fpassword;
        [Size(50)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        string fsistema;
        [Size(50)]
        public string sistema
        {
            get { return fsistema; }
            set { SetPropertyValue<string>(nameof(sistema), ref fsistema, value); }
        }
        Guid ftoken;
        public Guid token
        {
            get { return ftoken; }
            set { SetPropertyValue<Guid>(nameof(token), ref ftoken, value); }
        }
    }

}
