using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleAppAPIAuth.Model
{
    public enum EsitoSMS
    {
        //Status Value
        NonDefinito,
        WAITING,//	“WAITING” ATTESA
        SENT_TO_SMSC,// SENT_TO_SMSC,//	“SENT” INVIATO 
        WAIT4DLVR, //WAITING_DELIVERY,//	“WAIT4DLVR”   IN ATTESA DI CONSEGNA
        SENT,//	“SENT”  SPEDITO
        DLVRD,//DELIVERY_RECEIVED,//“DLVRD” "SPEDITO CONSEGNA RICEVUTA"
        TOOM4USER , //TOO_MANY_SMS_FROM_USER,//	“TOOM4USER”  TROPPI SMS DA UTENTE
        TOOM4NUM, //TOO_MANY_SMS_FOR_NUMBER,//“TOOM4NUM”    TROPPI SMS per numero telefonico 
        ERROR,//	“ERROR”
        TIMEOUT,//	“TIMEOUT”
        UNKNRCPT,// UNPARSABLE_RCPT,//	“UNKNRCPT”    PREFISSO SCONOSCIUTO
        UNKNPFX,// UNKNOWN_PREFIX,//“UNKNPFX”          PREFISSO SCONOSCIUTO
        DEMO,// SENT_IN_DEMO_MODE,//	“DEMO”
        SCHEDULED,// WAITING_DELAYED,//“SCHEDULED”    ATTESA RITARDATA ,   "PIANIFICATO"
        INVALIDDST,// INVALID_DESTINATION,//	“INVALIDDST”
        BLACKLISTED,//NUMBER_BLACKLISTED,//“BLACKLISTED”
        NUMBER_USER_BLACKLISTED,//NUMBER_USER_BLACKLISTED,//	“BLACKLISTED”
        SMSC_REJECTED,//	“KO”
        INVALID_CONTENTS,//“INVALIDCONTENTS”
    }
}
